---
- name: add gpg key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: adding source
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.c.list

- name: update ubuntu
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: latest

- name: kibana
  apt:
    name: kibana
    state: latest
    update_cache: yes

- name: install logstash
  apt:
    name: logstash
    state: present
    update_cache: yes
